/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f407_registers.h"
#include "i2c_driver.h"
#include "lcd_i2c.h"

int main(void)
{
    /* Initialize I2C1 */
    I2C1_Init();

    /* Initialize LCD */
    LCD_Init();

    /* First Line */
    LCD_SetCursor(0,0);
    LCD_SendString("Hello STM32");

    /* Second Line */
    LCD_SetCursor(1,0);
    LCD_SendString("Bare Metal");

    while(1)
    {

    }
}
