/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f407_registers.h"
#include "uart_dma.h"

char message[] =
"35_UART_DMA_BareMetal\r\n";

int main(void)
{
    UART2_Init();

    while(1)
    {
        UART_DMA_Send(message,
                      sizeof(message)-1);

        delay_ms(100);
    }
}
