/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f407_register.h"

/* ================= LED INIT ================= */
void LED_Init(void)
{
    RCC_AHB1ENR |= (1 << 3);   // GPIOD clock

    GPIOD_MODER &= ~(3 << (12 * 2));
    GPIOD_MODER |=  (1 << (12 * 2));
}

/* ================= LED TOGGLE ================= */
void LED_Toggle(void)
{
    GPIOD_ODR ^= (1 << 12);
}

/* ================= TIMER2 INIT ================= */
void TIM2_Init(void)
{
    RCC_APB1ENR |= (1 << 0);   // TIM2 clock enable

    TIM2_PSC = 16000 - 1;      // 16MHz / 16000 = 1kHz (1ms)
    TIM2_ARR = 1000 - 1;       // 1000ms = 1 second

    TIM2_DIER |= (1 << 0);     // Update interrupt enable

    TIM2_CR1 |= (1 << 0);      // Enable timer

    NVIC_ISER0 |= (1 << 28);   // Enable TIM2 interrupt in NVIC
}

/* ================= TIMER ISR ================= */
void TIM2_IRQHandler(void)
{
    if(TIM2_SR & 1)
    {
        TIM2_SR &= ~(1);       // clear flag
        LED_Toggle();         // toggle LED every 1 sec
    }
}

/* ================= MAIN ================= */
int main(void)
{
    LED_Init();
    TIM2_Init();

    while(1)
    {
        // CPU free (interrupt handles LED)
    }
}
